# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sandbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sandbox
  pod 'OperantKit'
  pod 'RxCocoa'
  pod 'RxSwift'

  target 'SandboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SandboxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
